services:
  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    volumes:
      - ./:/usr/src/app
      - node_modules:/usr/src/app/node_modules
    working_dir: /usr/src/app
    command: npm run test:silent
    depends_on:
      - db-test
    environment:
      - DB_HOST=db-test
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME_TEST}
      - JWT_SECRET=${JWT_SECRET}
      - NODE_ENV=test

  db-test:
    image: postgres:14
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', '${DB_USER}']
      interval: 5s
      timeout: 5s
      retries: 5
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME_TEST}
    ports:
      - '5433:5432'
    volumes:
      - postgres_test_data:/var/lib/postgresql/data

volumes:
  postgres_test_data:
  node_modules:
